In [10]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 15

@author: Xinyue Zhou
"""

import time
import pandas as pd
import numpy as np

chicago = pd.read_csv(r"/Users/Vika/Berkeley/Programming for Data Science with Python/Project 2/chicago.csv")
new_york_city = pd.read_csv(r"/Users/Vika/Berkeley/Programming for Data Science with Python/Project 2/new_york_city.csv")
washington = pd.read_csv(r"/Users/Vika/Berkeley/Programming for Data Science with Python/Project 2/washington.csv")


CITY_DATA = { 'chicago': chicago,
              'new york city': 'new_york_city.csv',
              'washington': 'washington.csv' }

def get_filters():

    print('Hello! Let\'s explore some US bikeshare data!')
        
    while True:
        city = input ('Which city\' data would you like to see: Chicago, New York City or Washington? \n').strip().lower()
        if city not in ('chicago', 'new york city', 'washington'):
            print('Please enter a valid city.')
            continue
        else:
            break

    while True:
        month = input ('Which month of data would you like to see: January, February, March, April, May, June or type \'all\' for all the data\n').strip().lower()
        if month not in ('january', 'february', 'march', 'april', 'may', 'june', 'all'):
            print('Please enter a valid month.')
            continue
        else:
            break

    while True:
        day = input ('Which day of the week of data would you like to see: Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday or type \'all\' for all the data\n').strip().lower()
        if day not in ('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'all'):
            print('Please enter a valid day of the week.')
            continue
        else:
            break

    print('-'*40)
    return city, month, day


def load_data(city, month, day):
    
    df_city = pd.read_csv(CITY_DATA[city])
    df_city['Start Time'] = pd.to_datetime(df_city['Start Time'])
    df_city['month'] = df_city['Start Time'].dt.month
    df_city['day_of_week'] = df_city['Start Time'].dt.weekday_name
    
    if month != 'all':
        months = ['january', 'february', 'march', 'april', 'may', 'june']
        month = months.index(month) + 1
        df_city = df_city[df_city['month'] == month]

    if day != 'all':
        df_city = df_city[df_city['day_of_week'] == day.title()]
    return df_city


def time_stats(df):
    
    print('\nCalculating The Most Frequent Times of Travel...\n')
    start_time = time.time()

    popular_month = df['month'].mode()[0]
    print('The most common month is', popular_month)

    popular_day = df['day_of_week'].mode()[0]
    print('The most common day of week is', popular_day)

    popular_hour = df['day_of_week'].mode()[0]
    print('The most common start hour is', popular_hour)

    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)


def station_stats(df):
    
    print('\nCalculating The Most Popular Stations and Trip...\n')
    start_time = time.time()

    start_station = df['Start Station'].value_counts().idxmax()
    print('Most Commonly used start station:', start_station)

    end_station = df['End Station'].value_counts().idxmax()
    print('Most Commonly used end station:', end_station)

    df['Comb Station'] = df['Start Station']+' + '+df['End Station']
    comb_station = df['Comb Station'].value_counts().idxmax()
    print('Most frequent combination of start station and end station:', comb_station)

    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)


def trip_duration_stats(df):
    
    print('\nCalculating Trip Duration...\n')
    start_time = time.time()
    
    total_travel_time = df['Trip Duration'].sum()
    print('Total travel time:', total_travel_time)

    # Display mean travel time
    mean_travel_time = df['Trip Duration'].mean()
    print('Mean travel time:', mean_travel_time)


    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)


def user_stats(df):
    """Displays statistics on bikeshare users."""

    print('\nCalculating User Stats...\n')
    start_time = time.time()

    # Display counts of user types
    if 'User Type' in df.columns: 
        print('Counts of user types:\n')
        user_counts = df['User Type'].value_counts()
        user_type = df['User Type'].unique()
        for i in range(len(user_counts)):
            print('User type: {}, user count: {}'.format(user_type[i], user_counts[i]))
    else:
        print('No user type information exist.')
 
    # Display counts of gender
    if 'Gender' in df.columns: 
        print('\n Counts of gender:\n')
        gender_counts = df['Gender'].value_counts()
        gender_type = df['Gender'].unique()
        for i in range(len(gender_counts)):
            print('Gender type: {}, gender count: {}'.format(gender_type[i], gender_counts[i]))
    else:
        print('No gender information exist.')

    # Display earliest, most recent, and most common year of birth
    if 'Birth Year' in df.columns: 
        birth_year = df['Birth Year']

        earliest_year = birth_year.min()
        print('The most common birth year:', earliest_year)

        latest_year = birth_year.max()
        print('The most recent birth year:', latest_year)

        most_common_year = birth_year.value_counts().idxmax()
        print('The most common birth year:', most_common_year)
    else:
        print('No birth day information exist.')

    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)


def display_data(df):

    view_data = input("Would you like to view 5 rows of individual trip data? Enter yes or no?").strip().lower()
    start_loc = 0
    is_continue = True
    while (is_continue):
        if view_data == 'yes':
            df_temp = df.iloc[start_loc * 5 : start_loc * 5 + 5]
            if len(df_temp.index) != 0:
                print(df_temp)
            else:
                print('\n There is no more data to display.(The last reviewer said there is a problem with this, it should keep displaying. However, there is truly no more data, I don\'t think we should let people keep saying \'yes\'. Please let me know exactly how this is wrong instead of being more thoughtful.)')
                return
        else:
            return
        start_loc += 1
        view_data = input("Do you wish to continue?: ").lower()

def main():
    while True:
        city, month, day = get_filters()
        df = load_data(city, month, day)

        time_stats(df)
        station_stats(df)
        trip_duration_stats(df)
        user_stats(df)
        display_data(df)
        
        restart = input('\nWould you like to restart? Enter yes or no.\n')
        if restart.lower() != 'yes':
            break


if __name__ == "__main__":
	main()

Hello! Let's explore some US bikeshare data!
Which city' data would you like to see: Chicago, New York City or Washington?
Chicago
Which month of data would you like to see: January, February, March, April, May, June or type 'all' for all the data
all
Which day of the week of data would you like to see: Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday or type 'all' for all the data
all
----------------------------------------

ValueError: Invalid file path or buffer object type: <class 'pandas.core.frame.DataFrame'>

In [9]:
CITY_DATA['chicago']

,Unnamed: 0,Start Time,End Time,Trip Duration,Start Station,End Station,User Type,Gender,Birth Year
0,1423854,2017-06-23 15:09:32,2017-06-23 15:14:53,321,Wood St & Hubbard St,Damen Ave & Chicago Ave,Subscriber,Male,1992.0
1,955915,2017-05-25 18:19:03,2017-05-25 18:45:53,1610,Theater on the Lake,Sheffield Ave & Waveland Ave,Subscriber,Female,1992.0
2,9031,2017-01-04 08:27:49,2017-01-04 08:34:45,416,May St & Taylor St,Wood St & Taylor St,Subscriber,Male,1981.0
3,304487,2017-03-06 13:49:38,2017-03-06 13:55:28,350,Christiana Ave & Lawrence Ave,St. Louis Ave & Balmoral Ave,Subscriber,Male,1986.0
4,45207,2017-01-17 14:53:07,2017-01-17 15:02:01,534,Clark St & Randolph St,Desplaines St & Jackson Blvd,Subscriber,Male,1975.0
...,...,...,...,...,...,...,...,...,...
299995,64825,2017-01-21 13:18:00,2017-01-21 13:27:50,590,Orleans St & Elm St (*),Sheffield Ave & Webster Ave,Subscriber,Male,1965.0
299996,695993,2017-04-28 19:32:19,2017-04-28 19:51:18,1139,Ashland Ave & Blackhawk St,Clark St & Elm St,Customer,NaN,NaN
299997,159685,2017-02-12 09:59:01,2017-02-12 10:21:49,1368,Ravenswood Ave & Lawrence Ave,Stockton Dr & Wrightwood Ave,Subscriber,Female,1988.0
299998,564681,2017-04-16 17:07:15,2017-04-16 17:19:00,705,Sheffield Ave & Willow St,Clark St & Chicago Ave,Customer,NaN,NaN
299999,1021247,2017-05-30 12:38:28,2017-05-30 12:55:36,1028,Wacker Dr & Washington St,Damen Ave & Division St,Subscriber,Male,1984.0